global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Controls.Platform;
global using Avalonia.Data;
global using Avalonia.Interactivity;
global using Avalonia.Platform;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Globalization;
global using System.Runtime.Versioning;
global using WebKit;
global using IosWebView = WebKit.WKWebView;
